(function() {var implementors = {};
implementors["glm"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseNum.html\" title=\"trait glm::BaseNum\">BaseNum</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Vector2.html\" title=\"struct glm::Vector2\">Vector2</a>&lt;T&gt;",synthetic:false,types:["glm::vec::vec::Vector2"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseNum.html\" title=\"trait glm::BaseNum\">BaseNum</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Vector3.html\" title=\"struct glm::Vector3\">Vector3</a>&lt;T&gt;",synthetic:false,types:["glm::vec::vec::Vector3"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseNum.html\" title=\"trait glm::BaseNum\">BaseNum</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Vector4.html\" title=\"struct glm::Vector4\">Vector4</a>&lt;T&gt;",synthetic:false,types:["glm::vec::vec::Vector4"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseFloat.html\" title=\"trait glm::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Matrix2.html\" title=\"struct glm::Matrix2\">Matrix2</a>&lt;T&gt;",synthetic:false,types:["glm::mat::mat::Matrix2"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseFloat.html\" title=\"trait glm::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Matrix3.html\" title=\"struct glm::Matrix3\">Matrix3</a>&lt;T&gt;",synthetic:false,types:["glm::mat::mat::Matrix3"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"glm/trait.BaseFloat.html\" title=\"trait glm::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"glm/struct.Matrix4.html\" title=\"struct glm::Matrix4\">Matrix4</a>&lt;T&gt;",synthetic:false,types:["glm::mat::mat::Matrix4"]},];
implementors["num_bigint"] = [{text:"impl <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"num_bigint/struct.BigUint.html\" title=\"struct num_bigint::BigUint\">BigUint</a>",synthetic:false,types:["num_bigint::biguint::BigUint"]},{text:"impl <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"num_bigint/struct.BigInt.html\" title=\"struct num_bigint::BigInt\">BigInt</a>",synthetic:false,types:["num_bigint::bigint::BigInt"]},];
implementors["num_complex"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"num_traits/trait.Num.html\" title=\"trait num_traits::Num\">Num</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"num_complex/struct.Complex.html\" title=\"struct num_complex::Complex\">Complex</a>&lt;T&gt;",synthetic:false,types:["num_complex::Complex"]},];
implementors["num_rational"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"num_integer/trait.Integer.html\" title=\"trait num_integer::Integer\">Integer</a>&gt; <a class=\"trait\" href=\"num_traits/identities/trait.One.html\" title=\"trait num_traits::identities::One\">One</a> for <a class=\"struct\" href=\"num_rational/struct.Ratio.html\" title=\"struct num_rational::Ratio\">Ratio</a>&lt;T&gt;",synthetic:false,types:["num_rational::Ratio"]},];
implementors["num_traits"] = [];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
